apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-svc
  namespace: fullstack-app
spec:
  selector:
    app: nginx-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  type: NodePort
