apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: fullstack-app
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
