apiVersion: v1
kind: Service
metadata:
  name: node-backend-svc
  namespace: fullstack-app
spec:
  selector:
    app: node-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
